-- =====================================================================
-- Ürün Risk Analizi - Veritabanı Şeması (PostgreSQL 15+ / pgvector)
-- =====================================================================
-- Her ürün kategorisi ayrı bir tabloda tutulur. Tablolar iki grup sütun
-- içerir:
--   1. Ürün verisi    : Trendyol'dan toplanan ham ürün bilgileri
--   2. Satıcı analizi : Veri hazırlama aşamasında Gemini ile üretilen,
--                       satıcıya yönelik metinsel analizler
--
-- Vektör (embedding) tabloları bu dosyada tanımlanmaz. Her kategori için
-- `<tablo>_embeddings` tablosu, kullanılan modelin boyutuna göre
-- backend/scripts/create_embeddings.py tarafından oluşturulur.
--
-- Not: Ham veri seti bu repoya dahil değildir.
-- =====================================================================

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS telefon_urunleri (
    id                         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Ürün verisi
    product_id                 VARCHAR(255),
    product_url                TEXT,
    platform                   VARCHAR(50) DEFAULT 'trendyol',
    name                       TEXT NOT NULL,
    brand                      VARCHAR(255),
    model                      VARCHAR(255),
    category                   VARCHAR(255),
    color                      VARCHAR(100),
    price                      NUMERIC(12, 2),
    rating                     NUMERIC(3, 2),
    sales_volume               INTEGER,
    seller_name                TEXT,
    stock_status               VARCHAR(50),
    availability               VARCHAR(50),
    shipping                   TEXT,
    description                TEXT,
    technical_summary          TEXT,

    -- Satıcı analizi (Gemini ile üretilmiş)
    seller_summary             TEXT,
    seller_description         TEXT,
    executive_summary          TEXT,
    profitability_analysis     TEXT,
    profit_margin_estimate     TEXT,
    monthly_revenue_estimate   TEXT,
    estimated_monthly_sales    TEXT,
    sales_performance          TEXT,
    competitive_positioning    TEXT,
    price_competitiveness      TEXT,
    competition_level          TEXT,
    market_demand              TEXT,
    growth_potential           TEXT,
    pricing_opportunities      TEXT,
    inventory_strategy         TEXT,
    customer_insights          TEXT,
    target_customer            TEXT,
    purchase_motivation        TEXT,
    marketing_angles           TEXT,
    search_keywords            TEXT,
    trending_status            TEXT,
    logistics_complexity       TEXT,
    operational_advice         TEXT,
    risk_management            TEXT,
    financial_projections      TEXT,
    seller_action_plan         TEXT,

    created_at                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_updated               TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Diğer kategoriler aynı yapıyı kullanır.
CREATE TABLE IF NOT EXISTS bilgisayar_urunleri (LIKE telefon_urunleri INCLUDING ALL);
CREATE TABLE IF NOT EXISTS klima_urunleri      (LIKE telefon_urunleri INCLUDING ALL);
CREATE TABLE IF NOT EXISTS kulaklik_urunleri   (LIKE telefon_urunleri INCLUDING ALL);

-- Filtreleme ve risk hesaplamalarında kullanılan sütunlar için indeksler.
CREATE INDEX IF NOT EXISTS telefon_urunleri_brand_idx    ON telefon_urunleri    (LOWER(brand));
CREATE INDEX IF NOT EXISTS bilgisayar_urunleri_brand_idx ON bilgisayar_urunleri (LOWER(brand));
CREATE INDEX IF NOT EXISTS klima_urunleri_brand_idx      ON klima_urunleri      (LOWER(brand));
CREATE INDEX IF NOT EXISTS kulaklik_urunleri_brand_idx   ON kulaklik_urunleri   (LOWER(brand));
