// Veritabanı sütun adlarının arayüzde gösterilecek Türkçe karşılıkları.
export const FIELD_LABELS = {
  availability: 'Tedarik Durumu',
  barrier_to_entry: 'Pazara Giriş Engeli',
  brand: 'Marka',
  break_even_time: 'Başabaş Noktası',
  cash_flow_impact: 'Nakit Akışı Etkisi',
  category: 'Kategori',
  color: 'Renk',
  competition_level: 'Rekabet Seviyesi',
  competitive_positioning: 'Rekabet Konumu',
  confidence_level: 'Güven Skoru',
  cost_optimization: 'Maliyet Optimizasyonu',
  created_at: 'Oluşturulma Tarihi',
  customer_insights: 'Müşteri Analizi',
  customer_satisfaction_risk: 'Müşteri Memnuniyeti Riski',
  decision: 'Karar',
  description: 'Ürün Açıklaması',
  differentiation_opportunity: 'Farklılaşma Fırsatı',
  estimated_monthly_sales: 'Tahmini Aylık Satış',
  executive_summary: 'Yönetici Özeti',
  exit_strategy: 'Çıkış Stratejisi',
  financial_projections: 'Mali Tahminler',
  future_outlook: 'Gelecek Beklentisi',
  growth_potential: 'Büyüme Potansiyeli',
  growth_strategies: 'Büyüme Stratejileri',
  id: 'Kayıt No',
  immediate_actions: 'Acil Eylemler',
  innovation_impact: 'Yenilik Etkisi',
  inventory_recommendation: 'Stok Tavsiyesi',
  inventory_strategy: 'Stok Stratejisi',
  last_updated: 'Son Güncelleme',
  logistics_complexity: 'Lojistik Karmaşıklığı',
  main_risks: 'Ana Riskler',
  market_demand: 'Pazar Talebi',
  market_saturation: 'Pazar Doygunluğu',
  marketing_angles: 'Pazarlama Açısı',
  marketing_focus: 'Pazarlama Odağı',
  mitigation_strategies: 'Risk Azaltma Stratejileri',
  model: 'Model',
  monthly_revenue_estimate: 'Aylık Gelir Tahmini',
  name: 'Ürün Adı',
  operational_advice: 'Operasyon Tavsiyeleri',
  overall_rating: 'Genel Derecelendirme',
  overall_risk_score: 'Risk Skoru',
  platform: 'Satış Platformu',
  price: 'Fiyat',
  price_category: 'Fiyat Segmenti',
  price_competitiveness: 'Fiyat Rekabeti',
  price_trend: 'Fiyat Eğilimi',
  pricing_opportunities: 'Fiyatlandırma Fırsatları',
  priority_level: 'Öncelik Seviyesi',
  product_id: 'Ürün Kimliği',
  product_url: 'Ürün Bağlantısı',
  profit_margin_estimate: 'Kâr Marjı Tahmini',
  profitability_analysis: 'Kârlılık Analizi',
  purchase_motivation: 'Satın Alma Motivasyonu',
  rating: 'Müşteri Puanı',
  return_risk: 'İade Riski',
  risk_management: 'Risk Yönetimi',
  roi_potential: 'Yatırım Getirisi Potansiyeli',
  sales_performance: 'Satış Performansı',
  sales_velocity: 'Satış Hızı',
  sales_volume: 'Satış Hacmi',
  search_keywords: 'Arama Etiketleri (SEO)',
  seasonality: 'Sezonsallık',
  seller_action_plan: 'Satıcı Eylem Planı',
  seller_description: 'Satıcı Açıklaması',
  seller_name: 'Satıcı',
  seller_summary: 'Satıcı Özeti',
  shipping: 'Kargo',
  stock_status: 'Stok Durumu',
  supplier_reliability: 'Tedarikçi Güvenilirliği',
  support_requirements: 'Destek Gereksinimi',
  target_customer: 'Hedef Müşteri',
  technical_summary: 'Teknik Özellikler',
  technology_lifecycle: 'Teknoloji Ömrü',
  trending_status: 'Trend Durumu',
  updated_at: 'Son Güncelleme',
};

export const getFieldLabel = (field) =>
  FIELD_LABELS[field] || field.replace(/_/g, ' ').replace(/\b\w/g, (char) => char.toUpperCase());
